name: newsbyte
description: "Flutter-powered news aggregator with swipeable interface, offering summarized content for quick and efficient reading."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  http: ^1.1.2
  flutter_image_compress: ^2.1.0
  image: ^4.1.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - config/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
